services:
  web:
    build: .
    # container_name: dungji-market-backend  # 타임스탬프 방식 사용으로 주석 처리
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - logs_volume:/app/logs
    ports:
      - "8001:8000"  # 좀비 컨테이너 우회용 임시 포트 변경
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=dungji_market_backend.settings
      - PYTHONUNBUFFERED=1
      - DEBUG=${DEBUG:-False}
      - USE_S3=${USE_S3:-True}
    restart: always

  # Nginx 서비스 추가 (정적 파일 서빙)
  # nginx:
  #   image: nginx:alpine
  #   volumes:
  #     - static_volume:/usr/share/nginx/html/static
  #     - media_volume:/usr/share/nginx/html/media
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - web
  #   restart: always

volumes:
  static_volume:
  media_volume:
  logs_volume: