version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=dungji_market_backend.settings
      - PYTHONUNBUFFERED=1
      - DEBUG=False
      - USE_S3=True
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,dungjimarket.com,www.dungjimarket.com,api.dungjimarket.com,54.180.82.238
    command: sh -c '
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn dungji_market_backend.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120 --reload'
    restart: always
    
  nginx:
    image: nginx:alpine
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: always

volumes:
  static_volume:
  media_volume: