# Generated by Django 4.2.19 on 2025-04-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupbuy",
            name="product_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="carrier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SKT", "SK텔레콤"),
                    ("KT", "KT"),
                    ("LGU", "LG U+"),
                    ("MVNO", "알뜰폰"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="contract_info",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="plan_info",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="registration_type",
            field=models.CharField(
                blank=True,
                choices=[("MNP", "번호이동"), ("NEW", "신규가입"), ("CHANGE", "기기변경")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="total_support_amount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
