# Generated by Django 4.2.16 on 2025-02-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sns_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="sns_type",
            field=models.CharField(
                choices=[("google", "Google"), ("kakao", "Kakao"), ("email", "Email")],
                default="email",
                max_length=10,
            ),
        ),
    ]
