# Generated by Django for NicknameChangeHistory model

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NicknameChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_nickname', models.CharField(max_length=15, verbose_name='이전 닉네임')),
                ('new_nickname', models.CharField(max_length=15, verbose_name='새 닉네임')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='변경 일시')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nickname_changes', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '닉네임 변경 이력',
                'verbose_name_plural': '닉네임 변경 이력',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='nicknamechangehistory',
            index=models.Index(fields=['user', '-changed_at'], name='api_nicknam_user_id_b8c9f6_idx'),
        ),
    ]