# Generated by Django 5.1.4 on 2025-04-15 06:55

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_groupbuy_product_name_product_carrier_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bid",
            options={
                "ordering": [
                    models.Case(
                        models.When(bid_type="price", then="amount"),
                        models.When(
                            bid_type="support",
                            then=django.db.models.expressions.CombinedExpression(
                                models.F("amount"), "*", models.Value(-1)
                            ),
                        ),
                        output_field=models.IntegerField(),
                    )
                ],
                "verbose_name": "입찰",
                "verbose_name_plural": "입찰 관리",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "카테고리", "verbose_name_plural": "카테고리 관리"},
        ),
        migrations.AlterModelOptions(
            name="groupbuy",
            options={"verbose_name": "공동구매", "verbose_name_plural": "공동구매 관리"},
        ),
        migrations.AlterModelOptions(
            name="participation",
            options={"verbose_name": "참여 정보", "verbose_name_plural": "참여 정보 관리"},
        ),
        migrations.AlterModelOptions(
            name="penalty",
            options={"verbose_name": "페널티", "verbose_name_plural": "페널티 관리"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "상품", "verbose_name_plural": "상품 관리"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "사용자", "verbose_name_plural": "사용자 관리"},
        ),
        migrations.AlterModelOptions(
            name="vote",
            options={"verbose_name": "투표", "verbose_name_plural": "투표 관리"},
        ),
        migrations.AlterField(
            model_name="bid",
            name="amount",
            field=models.PositiveIntegerField(default=0, verbose_name="입찰 금액"),
        ),
        migrations.AlterField(
            model_name="bid",
            name="bid_type",
            field=models.CharField(
                choices=[("price", "가격입찰"), ("support", "지원금입찰")],
                default="price",
                max_length=10,
                verbose_name="입찰 유형",
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="contract_period",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="약정 기간(월)"
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
        ),
        migrations.AlterField(
            model_name="bid",
            name="groupbuy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.groupbuy",
                verbose_name="공동구매",
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="is_selected",
            field=models.BooleanField(default=False, verbose_name="선택 여부"),
        ),
        migrations.AlterField(
            model_name="bid",
            name="seller",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="판매자",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_service",
            field=models.BooleanField(default=False, verbose_name="서비스 여부"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, verbose_name="카테고리명"),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.category",
                verbose_name="상위 카테고리",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(null=True, unique=True, verbose_name="슬러그"),
        ),
        migrations.AlterField(
            model_name="groupbuy",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_groupbuys",
                to=settings.AUTH_USER_MODEL,
                verbose_name="생성자",
            ),
        ),
        migrations.AlterField(
            model_name="groupbuy",
            name="current_participants",
            field=models.PositiveIntegerField(default=0, verbose_name="현재 참여자 수"),
        ),
        migrations.AlterField(
            model_name="groupbuy",
            name="description",
            field=models.TextField(blank=True, verbose_name="공구 설명"),
        ),
        migrations.AlterField(
            model_name="groupbuy",
            name="end_time",
            field=models.DateTimeField(verbose_name="종료 시간"),
        ),
        migrations.AlterField(
            model_name="groupbuy",
            name="max_participants",
            field=models.PositiveSmallIntegerField(
                default=100, verbose_name="최대 참여자 수"
            ),
        ),
        migrations.AlterField(
            model_name="groupbuy",
            name="min_participants",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="최소 참여자 수"),
        ),
        migrations.AlterField(
            model_name="groupbuy",
            name="participants",
            field=models.ManyToManyField(
                related_name="joined_groupbuys",
                through="api.Participation",
                to=settings.AUTH_USER_MODEL,
                verbose_name="참여자",
            ),
        ),
        migrations.AlterField(
            model_name="groupbuy",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.product",
                verbose_name="상품",
            ),
        ),
        migrations.AlterField(
            model_name="groupbuy",
            name="product_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="상품명 백업"),
        ),
        migrations.AlterField(
            model_name="groupbuy",
            name="start_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="시작 시간"
            ),
        ),
        migrations.AlterField(
            model_name="groupbuy",
            name="status",
            field=models.CharField(
                choices=[
                    ("recruiting", "모집중"),
                    ("bidding", "입찰진행중"),
                    ("voting", "최종선택중"),
                    ("seller_confirmation", "판매자확정대기"),
                    ("completed", "완료"),
                    ("cancelled", "취소됨"),
                ],
                default="recruiting",
                max_length=20,
                verbose_name="상태",
            ),
        ),
        migrations.AlterField(
            model_name="groupbuy",
            name="target_price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="목표 가격"
            ),
        ),
        migrations.AlterField(
            model_name="groupbuy",
            name="title",
            field=models.CharField(max_length=255, verbose_name="공구 제목"),
        ),
        migrations.AlterField(
            model_name="groupbuy",
            name="voting_end",
            field=models.DateTimeField(blank=True, null=True, verbose_name="투표 종료 시간"),
        ),
        migrations.AlterField(
            model_name="participation",
            name="groupbuy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.groupbuy",
                verbose_name="공동구매",
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="is_leader",
            field=models.BooleanField(default=False, verbose_name="리더 여부"),
        ),
        migrations.AlterField(
            model_name="participation",
            name="is_locked",
            field=models.BooleanField(default=False, verbose_name="잠금 여부"),
        ),
        migrations.AlterField(
            model_name="participation",
            name="joined_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="참여 시간"),
        ),
        migrations.AlterField(
            model_name="participation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="count",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="누적 횟수"),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="end_date",
            field=models.DateTimeField(verbose_name="종료일"),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="활성화 여부"),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="penalty_type",
            field=models.CharField(max_length=20, verbose_name="페널티 유형"),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="reason",
            field=models.TextField(verbose_name="사유"),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="시작일"
            ),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="base_price",
            field=models.PositiveIntegerField(verbose_name="기본 가격"),
        ),
        migrations.AlterField(
            model_name="product",
            name="carrier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SKT", "SK텔레콤"),
                    ("KT", "KT"),
                    ("LGU", "LG U+"),
                    ("MVNO", "알뜻폰"),
                ],
                max_length=10,
                null=True,
                verbose_name="통신사",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="api.category",
                verbose_name="카테고리",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="카테고리명"),
        ),
        migrations.AlterField(
            model_name="product",
            name="contract_info",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="계약 정보"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="상품 설명"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.URLField(verbose_name="이미지 URL"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(default=True, verbose_name="판매 가능 여부"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="상품명"),
        ),
        migrations.AlterField(
            model_name="product",
            name="plan_info",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="요금제 정보"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("device", "기기"), ("service", "통신/서비스")],
                max_length=10,
                verbose_name="상품 유형",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="registration_type",
            field=models.CharField(
                blank=True,
                choices=[("MNP", "번호이동"), ("NEW", "신규가입"), ("CHANGE", "기기변경")],
                max_length=10,
                null=True,
                verbose_name="가입 유형",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="release_date",
            field=models.DateField(blank=True, null=True, verbose_name="출시일"),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="슬러그"),
        ),
        migrations.AlterField(
            model_name="product",
            name="total_support_amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="총 지원금"
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="choice",
            field=models.CharField(
                choices=[("confirm", "확정"), ("cancel", "포기")],
                max_length=10,
                verbose_name="선택",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="participation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.participation",
                verbose_name="참여 정보",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="voted_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="투표 시간"),
        ),
    ]
