# Generated by Django 4.2.19 on 2025-04-23 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_bid_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="carrier",
        ),
        migrations.RemoveField(
            model_name="product",
            name="contract_info",
        ),
        migrations.RemoveField(
            model_name="product",
            name="plan_info",
        ),
        migrations.RemoveField(
            model_name="product",
            name="registration_type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="total_support_amount",
        ),
        migrations.AddField(
            model_name="category",
            name="detail_type",
            field=models.CharField(
                choices=[
                    ("none", "기본"),
                    ("telecom", "통신"),
                    ("electronics", "가전"),
                    ("rental", "렌탈"),
                    ("subscription", "구독"),
                ],
                default="none",
                max_length=20,
                verbose_name="상세 정보 유형",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="required_fields",
            field=models.JSONField(blank=True, default=dict, verbose_name="필수 필드"),
        ),
        migrations.AddField(
            model_name="product",
            name="attributes",
            field=models.JSONField(blank=True, default=dict, verbose_name="상품 특성"),
        ),
        migrations.CreateModel(
            name="TelecomProductDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        choices=[
                            ("SKT", "SK텔레콤"),
                            ("KT", "KT"),
                            ("LGU", "LG U+"),
                            ("MVNO", "알뜻폰"),
                        ],
                        max_length=10,
                        verbose_name="통신사",
                    ),
                ),
                (
                    "registration_type",
                    models.CharField(
                        choices=[("MNP", "번호이동"), ("NEW", "신규가입"), ("CHANGE", "기기변경")],
                        max_length=10,
                        verbose_name="가입 유형",
                    ),
                ),
                ("plan_info", models.CharField(max_length=255, verbose_name="요금제 정보")),
                (
                    "contract_info",
                    models.CharField(max_length=255, verbose_name="계약 정보"),
                ),
                (
                    "total_support_amount",
                    models.PositiveIntegerField(verbose_name="총 지원금"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telecom_detail",
                        to="api.product",
                        verbose_name="상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "통신 상품 상세",
                "verbose_name_plural": "통신 상품 상세 관리",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionProductDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "월간"),
                            ("quarterly", "분기"),
                            ("yearly", "연간"),
                        ],
                        max_length=20,
                        verbose_name="결제 주기",
                    ),
                ),
                (
                    "auto_renewal",
                    models.BooleanField(default=True, verbose_name="자동 갱신"),
                ),
                (
                    "free_trial_days",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="무료 체험 기간(일)"
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_detail",
                        to="api.product",
                        verbose_name="상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "구독 상품 상세",
                "verbose_name_plural": "구독 상품 상세 관리",
            },
        ),
        migrations.CreateModel(
            name="StandardProductDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, verbose_name="브랜드"),
                ),
                (
                    "origin",
                    models.CharField(blank=True, max_length=100, verbose_name="원산지"),
                ),
                (
                    "shipping_fee",
                    models.PositiveIntegerField(default=0, verbose_name="배송비"),
                ),
                (
                    "shipping_info",
                    models.CharField(blank=True, max_length=255, verbose_name="배송 정보"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standard_detail",
                        to="api.product",
                        verbose_name="상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "일반 상품 상세",
                "verbose_name_plural": "일반 상품 상세 관리",
            },
        ),
        migrations.CreateModel(
            name="RentalProductDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rental_period_options", models.JSONField(verbose_name="렌탈 기간 옵션")),
                (
                    "maintenance_info",
                    models.TextField(blank=True, verbose_name="유지보수 정보"),
                ),
                (
                    "deposit_amount",
                    models.PositiveIntegerField(default=0, verbose_name="보증금"),
                ),
                ("monthly_fee", models.PositiveIntegerField(verbose_name="월 이용료")),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_detail",
                        to="api.product",
                        verbose_name="상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "렌탈 상품 상세",
                "verbose_name_plural": "렌탈 상품 상세 관리",
            },
        ),
        migrations.CreateModel(
            name="ProductCustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100, verbose_name="필드명")),
                ("field_label", models.CharField(max_length=100, verbose_name="표시명")),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "텍스트"),
                            ("number", "숫자"),
                            ("boolean", "예/아니오"),
                            ("select", "선택"),
                            ("date", "날짜"),
                        ],
                        max_length=20,
                        verbose_name="필드 타입",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="필수 여부"),
                ),
                (
                    "options",
                    models.JSONField(blank=True, default=list, verbose_name="선택 옵션"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fields",
                        to="api.category",
                        verbose_name="카테고리",
                    ),
                ),
            ],
            options={
                "verbose_name": "상품 커스텀 필드",
                "verbose_name_plural": "상품 커스텀 필드 관리",
                "unique_together": {("category", "field_name")},
            },
        ),
        migrations.CreateModel(
            name="ElectronicsProductDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manufacturer", models.CharField(max_length=100, verbose_name="제조사")),
                (
                    "warranty_period",
                    models.PositiveSmallIntegerField(verbose_name="보증 기간(개월)"),
                ),
                (
                    "power_consumption",
                    models.CharField(blank=True, max_length=50, verbose_name="소비 전력"),
                ),
                (
                    "dimensions",
                    models.CharField(blank=True, max_length=100, verbose_name="제품 크기"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="electronics_detail",
                        to="api.product",
                        verbose_name="상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "가전 제품 상세",
                "verbose_name_plural": "가전 제품 상세 관리",
            },
        ),
        migrations.CreateModel(
            name="ProductCustomValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_value",
                    models.TextField(blank=True, null=True, verbose_name="텍스트 값"),
                ),
                (
                    "number_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="숫자 값",
                    ),
                ),
                (
                    "boolean_value",
                    models.BooleanField(blank=True, null=True, verbose_name="불리언 값"),
                ),
                (
                    "date_value",
                    models.DateField(blank=True, null=True, verbose_name="날짜 값"),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.productcustomfield",
                        verbose_name="필드",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_values",
                        to="api.product",
                        verbose_name="상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "상품 커스텀 값",
                "verbose_name_plural": "상품 커스텀 값 관리",
                "unique_together": {("product", "field")},
            },
        ),
    ]
