# Generated by Django 4.2.19 on 2025-04-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_product_carrier_remove_product_contract_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupbuy",
            name="product_details",
            field=models.JSONField(blank=True, null=True, verbose_name="상품 세부 정보"),
        ),
        migrations.AddField(
            model_name="groupbuy",
            name="region_type",
            field=models.CharField(
                choices=[("local", "지역"), ("nationwide", "전국(비대면)")],
                default="local",
                max_length=20,
                verbose_name="지역 유형",
            ),
        ),
        migrations.AlterField(
            model_name="telecomproductdetail",
            name="carrier",
            field=models.CharField(
                choices=[
                    ("SKT", "SK텔레콤"),
                    ("KT", "KT"),
                    ("LGU", "LG U+"),
                    ("MVNO", "알뜰폰"),
                ],
                max_length=10,
                verbose_name="통신사",
            ),
        ),
    ]
