# Generated by Django 4.2.19 on 2025-04-30 07:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_review_wishlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telecomproductdetail",
            name="total_support_amount",
        ),
    ]
