# Generated by Django 4.2.19 on 2025-04-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_remove_telecomproductdetail_total_support_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupbuy",
            name="plan_info",
            field=models.CharField(
                blank=True,
                choices=[
                    ("5G_basic", "5G 기본(3만원대)"),
                    ("5G_standard", "5G 일반(5만원대)"),
                    ("5G_premium", "5G 프리미엄(7만원대)"),
                    ("5G_special", "5G 특별(9만원대)"),
                    ("5G_platinum", "5G 플래티넘(10만원대)"),
                ],
                max_length=20,
                null=True,
                verbose_name="요금제",
            ),
        ),
        migrations.AddField(
            model_name="groupbuy",
            name="subscription_type",
            field=models.CharField(
                blank=True,
                choices=[("new", "신규가입"), ("transfer", "번호이동"), ("change", "기기변경")],
                max_length=20,
                null=True,
                verbose_name="가입유형",
            ),
        ),
        migrations.AddField(
            model_name="groupbuy",
            name="telecom_carrier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SKT", "SKT"),
                    ("KT", "KT"),
                    ("LGU", "LG U+"),
                    ("MVNO", "알트"),
                ],
                max_length=20,
                null=True,
                verbose_name="통신사",
            ),
        ),
        migrations.AlterField(
            model_name="groupbuy",
            name="product_details",
            field=models.JSONField(blank=True, null=True, verbose_name="기타 세부 정보"),
        ),
    ]
