# Generated by Django 4.2.19 on 2025-04-30 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_groupbuy_plan_info_groupbuy_subscription_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupbuy",
            name="plan_info",
        ),
        migrations.RemoveField(
            model_name="groupbuy",
            name="subscription_type",
        ),
        migrations.RemoveField(
            model_name="groupbuy",
            name="telecom_carrier",
        ),
        migrations.CreateModel(
            name="GroupBuyTelecomDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telecom_carrier",
                    models.CharField(
                        choices=[
                            ("SKT", "SKT"),
                            ("KT", "KT"),
                            ("LGU", "LG U+"),
                            ("MVNO", "알뜰폰"),
                        ],
                        max_length=20,
                        verbose_name="통신사",
                    ),
                ),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[
                            ("new", "신규가입"),
                            ("transfer", "번호이동"),
                            ("change", "기기변경"),
                        ],
                        max_length=20,
                        verbose_name="가입유형",
                    ),
                ),
                (
                    "plan_info",
                    models.CharField(
                        choices=[
                            ("3만원대", "3만원대"),
                            ("5만원대", "5만원대"),
                            ("7만원대", "7만원대"),
                            ("9만원대", "9만원대"),
                            ("10만원대", "10만원대"),
                        ],
                        max_length=20,
                        verbose_name="요금제",
                    ),
                ),
                (
                    "contract_period",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="약정기간"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "groupbuy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telecom_detail",
                        to="api.groupbuy",
                        verbose_name="공구",
                    ),
                ),
            ],
            options={
                "verbose_name": "공구 통신 세부정보",
                "verbose_name_plural": "공구 통신 세부정보 관리",
            },
        ),
    ]
