# Generated by Django 4.2.19 on 2025-05-03 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_remove_groupbuy_plan_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="message",
            field=models.TextField(blank=True, verbose_name="입찰 메시지"),
        ),
        migrations.AddField(
            model_name="bid",
            name="status",
            field=models.CharField(
                choices=[("pending", "대기중"), ("selected", "확정"), ("rejected", "포기")],
                default="pending",
                max_length=20,
                verbose_name="상태",
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정 시간"),
        ),
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.PositiveIntegerField(verbose_name="총 금액")),
                ("fee_amount", models.PositiveIntegerField(verbose_name="수수료")),
                ("net_amount", models.PositiveIntegerField(verbose_name="실 정산액")),
                ("settlement_date", models.DateTimeField(verbose_name="정산일")),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "처리중"),
                            ("completed", "정산완료"),
                            ("failed", "정산실패"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="정산 상태",
                    ),
                ),
                (
                    "receipt_url",
                    models.URLField(blank=True, null=True, verbose_name="영수증 URL"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 시간"),
                ),
                (
                    "bid",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settlement",
                        to="api.bid",
                        verbose_name="입찰",
                    ),
                ),
                (
                    "groupbuy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="api.groupbuy",
                        verbose_name="공동구매",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="판매자",
                    ),
                ),
            ],
            options={
                "verbose_name": "정산 내역",
                "verbose_name_plural": "정산 내역 관리",
                "ordering": ["-settlement_date"],
            },
        ),
    ]
