# Generated by Django 4.2.19 on 2025-05-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_bid_message_bid_status_bid_updated_at_settlement"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupbuy",
            name="creator_nickname",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="생성자 닉네임"
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="참여 닉네임"
            ),
        ),
    ]
