# Generated by Django 4.2.19 on 2025-06-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_groupbuy_creator_nickname_participation_nickname"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="groupbuy",
            name="unique_groupbuy_per_product",
        ),
        migrations.AddConstraint(
            model_name="groupbuy",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["recruiting", "bidding", "voting", "seller_confirmation"],
                    )
                ),
                fields=("product", "creator"),
                name="unique_active_groupbuy_per_product",
            ),
        ),
    ]
