# Generated by Django 4.2.19 on 2025-06-18 07:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_remove_groupbuy_unique_groupbuy_per_product_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="groupbuy",
            name="unique_active_groupbuy_per_product",
        ),
    ]
