# Generated by Django 3.2.11 on 2025-07-08 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_groupbuy_unique_active_groupbuy_per_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidTokenPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(choices=[('standard', '기본 입찰권'), ('premium', '프리미엄 입찰권'), ('unlimited', '무제한 입찰권')], max_length=20, verbose_name='입찰권 유형')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='수량')),
                ('total_price', models.PositiveIntegerField(verbose_name='결제 금액')),
                ('payment_status', models.CharField(choices=[('pending', '결제 대기'), ('completed', '결제 완료'), ('cancelled', '취소됨'), ('refunded', '환불됨')], default='pending', max_length=20, verbose_name='결제 상태')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='구매일')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='결제일')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_purchases', to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
            ],
            options={
                'verbose_name': '입찰권 구매 내역',
                'verbose_name_plural': '입찰권 구매 내역 관리',
            },
        ),
        migrations.CreateModel(
            name='BidToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(choices=[('standard', '기본 입찰권'), ('premium', '프리미엄 입찰권'), ('unlimited', '무제한 입찰권')], default='standard', max_length=20, verbose_name='입찰권 유형')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('expires_at', models.DateTimeField(verbose_name='만료일')),
                ('status', models.CharField(choices=[('active', '활성'), ('used', '사용됨'), ('expired', '만료됨')], default='active', max_length=20, verbose_name='상태')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='사용일')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_tokens', to=settings.AUTH_USER_MODEL, verbose_name='판매자')),
                ('used_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_used', to='api.bid', verbose_name='사용된 입찰')),
            ],
            options={
                'verbose_name': '입찰권',
                'verbose_name_plural': '입찰권 관리',
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids', to='api.bidtoken', verbose_name='사용된 입찰권'),
        ),
    ]
