# Generated by Django 3.2.11 on 2025-07-11 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20250708_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='법정동코드')),
                ('name', models.CharField(max_length=100, verbose_name='지역명')),
                ('full_name', models.CharField(max_length=200, verbose_name='전체 지역명')),
                ('level', models.IntegerField(choices=[(0, '시/도'), (1, '시/군/구'), (2, '읍/면/동')], verbose_name='지역 레벨')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.region', verbose_name='상위 지역')),
            ],
            options={
                'verbose_name': '지역',
                'verbose_name_plural': '지역 목록',
                'ordering': ['code'],
            },
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['code'], name='api_region_code_e6653e_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['parent'], name='api_region_parent__d883b9_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['level'], name='api_region_level_5f7a9d_idx'),
        ),
    ]
