# Generated by Django 5.1.4 on 2025-07-11 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_auto_20250711_1600"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupbuy",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groupbuys",
                to="api.region",
                verbose_name="지역",
            ),
        ),
        migrations.AddField(
            model_name="groupbuy",
            name="region_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="지역명 백업"
            ),
        ),
    ]
