# Generated by Django 5.1.4 on 2025-07-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_groupbuy_region_groupbuy_region_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("reminder", "리마인더"),
                    ("success", "성공/최종선정"),
                    ("failure", "실패/취소"),
                    ("info", "정보/상태변경"),
                ],
                default="info",
                max_length=20,
            ),
        ),
    ]
