# Generated by Django 5.1.4 on 2025-07-13 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address_detail",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="상세 주소"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="address_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="api.region",
                verbose_name="사업장 지역",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="business_license_image",
            field=models.URLField(blank=True, null=True, verbose_name="사업자등록증 이미지"),
        ),
        migrations.AddField(
            model_name="user",
            name="delivery_history_image",
            field=models.URLField(blank=True, null=True, verbose_name="택배 송장 이미지"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_remote_sales_enabled",
            field=models.BooleanField(default=False, verbose_name="비대면 판매 가능 여부"),
        ),
        migrations.AddField(
            model_name="user",
            name="remote_sales_expiry_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="비대면 인증 만료일"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="remote_sales_verification_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="비대면 인증일"),
        ),
        migrations.AddField(
            model_name="user",
            name="remote_sales_verified",
            field=models.BooleanField(default=False, verbose_name="비대면 판매 인증 완료"),
        ),
        migrations.AlterField(
            model_name="bid",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "대기중"),
                    ("selected", "확정"),
                    ("rejected", "포기"),
                    ("ineligible", "자격미달"),
                ],
                default="pending",
                max_length=20,
                verbose_name="상태",
            ),
        ),
        migrations.CreateModel(
            name="GroupBuyRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "groupbuy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="api.groupbuy",
                        verbose_name="공구",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groupbuy_regions",
                        to="api.region",
                        verbose_name="지역",
                    ),
                ),
            ],
            options={
                "verbose_name": "공구 지역",
                "verbose_name_plural": "공구 지역 관리",
                "unique_together": {("groupbuy", "region")},
            },
        ),
    ]
