# Generated by Django 5.1.4 on 2025-07-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_user_address_detail_user_address_region_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupbuytelecomdetail",
            name="contract_period",
            field=models.CharField(default="24개월", max_length=20, verbose_name="약정기간"),
        ),
    ]
