# Generated by Django 3.2.11 on 2025-07-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_groupbuytelecomdetail_contract_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidtoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='만료일'),
        ),
        migrations.AlterField(
            model_name='bidtoken',
            name='token_type',
            field=models.CharField(choices=[('single', '입찰권 단품'), ('unlimited', '무제한 구독권')], default='standard', max_length=20, verbose_name='입찰권 유형'),
        ),
        migrations.AlterField(
            model_name='bidtokenpurchase',
            name='token_type',
            field=models.CharField(choices=[('single', '입찰권 단품'), ('unlimited', '무제한 구독권')], max_length=20, verbose_name='입찰권 유형'),
        ),
    ]
