# Generated by Django 5.1.4 on 2025-07-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_auto_20250715_1734"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/", verbose_name="상품 이미지"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, verbose_name="이미지 URL"),
        ),
    ]
