# Generated by Django 3.2.11 on 2025-07-19 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_product_image_alter_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('agreed', '동의'), ('disagreed', '거부'), ('expired', '만료')], default='pending', max_length=20, verbose_name='동의 상태')),
                ('agreed_at', models.DateTimeField(blank=True, null=True, verbose_name='동의 시간')),
                ('disagreed_at', models.DateTimeField(blank=True, null=True, verbose_name='거부 시간')),
                ('consent_deadline', models.DateTimeField(verbose_name='동의 마감 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='api.bid', verbose_name='선택된 입찰')),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='api.participation', verbose_name='참여')),
            ],
            options={
                'verbose_name': '참여자 동의',
                'verbose_name_plural': '참여자 동의 관리',
                'ordering': ['-created_at'],
            },
        ),
    ]
