# Generated by Django 3.2.11 on 2025-07-20 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_participantconsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='휴대폰 번호')),
                ('verification_code', models.CharField(max_length=6, verbose_name='인증 코드')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('verified', '인증완료'), ('expired', '만료됨'), ('failed', '실패')], default='pending', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('expires_at', models.DateTimeField(verbose_name='만료일시')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='인증일시')),
                ('attempt_count', models.IntegerField(default=0, verbose_name='시도 횟수')),
                ('max_attempts', models.IntegerField(default=5, verbose_name='최대 시도 횟수')),
                ('purpose', models.CharField(default='signup', help_text='signup: 회원가입, reset_password: 비밀번호 재설정, change_phone: 전화번호 변경', max_length=50, verbose_name='용도')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_verifications', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '휴대폰 인증',
                'verbose_name_plural': '휴대폰 인증',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='phoneverification',
            index=models.Index(fields=['phone_number', 'status'], name='api_phoneve_phone_n_a85253_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneverification',
            index=models.Index(fields=['verification_code'], name='api_phoneve_verific_0bc55f_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneverification',
            index=models.Index(fields=['created_at'], name='api_phoneve_created_de46fa_idx'),
        ),
    ]
