# Generated by Django 3.2.11 on 2025-07-22 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_phone_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='투표 일시')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.bid', verbose_name='선택한 입찰')),
                ('groupbuy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_votes', to='api.groupbuy', verbose_name='공구')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_votes', to=settings.AUTH_USER_MODEL, verbose_name='투표자')),
            ],
            options={
                'verbose_name': '입찰 투표',
                'verbose_name_plural': '입찰 투표 목록',
                'unique_together': {('participant', 'groupbuy')},
            },
        ),
    ]
