# Generated by Django 3.2.11 on 2025-07-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_bidvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', help_text='사용자가 표시될 이름', max_length=100, verbose_name='닉네임'),
        ),
    ]
