# Generated by Django 3.2.11 on 2025-07-23 04:33

from django.db import migrations


def migrate_first_name_to_nickname(apps, schema_editor):
    """first_name 필드의 값을 nickname 필드로 복사"""
    User = apps.get_model('api', 'User')
    for user in User.objects.all():
        if user.first_name:
            user.nickname = user.first_name
        else:
            # first_name이 없는 경우 username의 @ 앞부분을 사용
            if '@' in user.username:
                user.nickname = user.username.split('@')[0]
            else:
                user.nickname = user.username
        user.save()


def reverse_migrate(apps, schema_editor):
    """마이그레이션 되돌리기"""
    User = apps.get_model('api', 'User')
    for user in User.objects.all():
        user.nickname = ''
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_user_nickname'),
    ]

    operations = [
        migrations.RunPython(migrate_first_name_to_nickname, reverse_migrate),
    ]
