# Generated by Django 3.2.11 on 2025-07-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_migrate_first_name_to_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_address_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='사업장 시/군/구'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_address_province',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='사업장 시/도'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='사업자등록번호'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_remote_sales',
            field=models.BooleanField(default=False, verbose_name='비대면 판매 가능'),
        ),
    ]
