# Generated by Django 3.2.11 on 2025-07-23 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_seller_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business_address_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_address_province',
        ),
        migrations.AlterField(
            model_name='user',
            name='address_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.region', verbose_name='활동 지역'),
        ),
    ]
