# Generated by Django 3.2.11 on 2025-07-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_business_address_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='final_decision',
            field=models.CharField(choices=[('pending', '대기중'), ('confirmed', '판매확정'), ('cancelled', '판매포기')], default='pending', max_length=20, verbose_name='최종선택'),
        ),
        migrations.AddField(
            model_name='bid',
            name='final_decision_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='최종선택 일시'),
        ),
        migrations.AddField(
            model_name='participation',
            name='final_decision',
            field=models.CharField(choices=[('pending', '대기중'), ('confirmed', '구매확정'), ('cancelled', '구매포기')], default='pending', max_length=20, verbose_name='최종선택'),
        ),
        migrations.AddField(
            model_name='participation',
            name='final_decision_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='최종선택 일시'),
        ),
    ]
