# Generated by Django 3.2.11 on 2025-07-28 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20250728_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoShowReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('buyer_noshow', '구매자 노쇼'), ('seller_noshow', '판매자 노쇼')], max_length=20, verbose_name='신고 유형')),
                ('content', models.TextField(verbose_name='신고 내용')),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='noshow_reports/', verbose_name='증빙 이미지')),
                ('status', models.CharField(choices=[('pending', '검토중'), ('confirmed', '확인됨'), ('rejected', '반려됨')], default='pending', max_length=20, verbose_name='처리 상태')),
                ('admin_comment', models.TextField(blank=True, verbose_name='관리자 코멘트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신고일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일')),
                ('bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noshow_reports', to='api.bid', verbose_name='입찰 정보')),
                ('groupbuy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noshow_reports', to='api.groupbuy', verbose_name='공동구매')),
                ('participation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noshow_reports', to='api.participation', verbose_name='참여 정보')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_noshow_reports', to=settings.AUTH_USER_MODEL, verbose_name='처리자')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noshow_reports_received', to=settings.AUTH_USER_MODEL, verbose_name='피신고자')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noshow_reports_made', to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
            ],
            options={
                'verbose_name': '노쇼 신고',
                'verbose_name_plural': '노쇼 신고 관리',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='noshowreport',
            constraint=models.UniqueConstraint(fields=('reporter', 'reported_user', 'groupbuy'), name='unique_noshow_report_per_user_groupbuy'),
        ),
    ]
