# Generated by Django 3.2.11 on 2025-07-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20250728_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverification',
            name='additional_info',
            field=models.JSONField(blank=True, default=dict, help_text='인증 시 제공된 추가 정보 (이름, 생년월일, 성별 등)', verbose_name='추가 정보'),
        ),
    ]
