# Generated by Django 3.2.11 on 2025-07-31 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_add_phone_verification_additional_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='이벤트 제목')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='슬러그')),
                ('event_type', models.CharField(choices=[('discount', '할인 이벤트'), ('gift', '사은품 이벤트'), ('point', '포인트 이벤트'), ('special', '특별 이벤트'), ('notice', '공지사항')], default='special', max_length=20, verbose_name='이벤트 타입')),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('scheduled', '예정'), ('ongoing', '진행중'), ('ended', '종료')], default='draft', max_length=20, verbose_name='상태')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='events/thumbnails/', verbose_name='썸네일 이미지')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, verbose_name='썸네일 URL')),
                ('content_image', models.ImageField(blank=True, null=True, upload_to='events/content/', verbose_name='본문 이미지')),
                ('content_image_url', models.URLField(blank=True, max_length=500, verbose_name='본문 이미지 URL')),
                ('content', models.TextField(help_text='HTML 사용 가능', verbose_name='이벤트 내용')),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='간단 설명')),
                ('start_date', models.DateTimeField(verbose_name='시작일')),
                ('end_date', models.DateTimeField(verbose_name='종료일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '이벤트',
                'verbose_name_plural': '이벤트',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='배너 제목')),
                ('banner_type', models.CharField(choices=[('event', '이벤트'), ('notice', '공지사항'), ('promotion', '프로모션')], default='event', max_length=20, verbose_name='배너 타입')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='배너 이미지')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='배너 이미지 URL')),
                ('link_url', models.URLField(blank=True, help_text='외부 링크 URL (선택사항)', max_length=500, verbose_name='링크 URL')),
                ('order', models.IntegerField(default=0, help_text='낮은 숫자가 먼저 표시됩니다', verbose_name='표시 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='시작일')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_banners', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='api.event', verbose_name='연결된 이벤트')),
            ],
            options={
                'verbose_name': '배너',
                'verbose_name_plural': '배너',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
