# Generated by Django 3.2.11 on 2025-08-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_banner_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbuy',
            name='status',
            field=models.CharField(choices=[('recruiting', '모집중'), ('bidding', '입찰진행중'), ('voting', '투표중'), ('final_selection', '최종선택중'), ('seller_confirmation', '판매자확정대기'), ('completed', '완료'), ('cancelled', '취소됨')], default='recruiting', max_length=20, verbose_name='상태'),
        ),
    ]
