# Generated by Django 3.2.11 on 2025-08-01 15:02

from django.db import migrations


def update_user_roles(apps, schema_editor):
    """
    기존 'user' role을 'buyer'로 변경
    """
    User = apps.get_model('api', 'User')
    
    # 'user' role을 가진 모든 사용자를 'buyer'로 변경
    updated_count = User.objects.filter(role='user').update(role='buyer')
    print(f"Updated {updated_count} users from 'user' to 'buyer' role")


def reverse_user_roles(apps, schema_editor):
    """
    역방향 마이그레이션: 'buyer'를 'user'로 되돌림
    """
    User = apps.get_model('api', 'User')
    
    # 'buyer' role을 가진 사용자 중에서 seller나 admin이 아닌 것들을 'user'로 변경
    # 하지만 이 역방향은 권장하지 않음
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_groupbuy_status'),
    ]

    operations = [
        migrations.RunPython(update_user_roles, reverse_user_roles),
    ]
