# Generated by Django 3.2.11 on 2025-08-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20250801_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbuy',
            name='final_selection_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='최종선택 종료 시간'),
        ),
    ]
