# Generated by Django 5.1.4 on 2025-08-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0036_groupbuy_final_selection_end"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupbuy",
            name="voting_end",
        ),
        migrations.AlterField(
            model_name="groupbuy",
            name="status",
            field=models.CharField(
                choices=[
                    ("recruiting", "모집중"),
                    ("bidding", "입찰진행중"),
                    ("final_selection", "최종선택중"),
                    ("seller_confirmation", "판매자확정대기"),
                    ("completed", "완료"),
                    ("cancelled", "취소됨"),
                ],
                default="recruiting",
                max_length=20,
                verbose_name="상태",
            ),
        ),
        migrations.DeleteModel(
            name="BidVote",
        ),
    ]
