# Generated by Django 3.2.11 on 2025-08-05 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_voting_end_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
