# Generated by Django 3.2.11 on 2025-08-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_vote_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbuy',
            name='seller_selection_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='판매자 최종선택 종료 시간'),
        ),
        migrations.AlterField(
            model_name='groupbuy',
            name='final_selection_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='구매자 최종선택 종료 시간'),
        ),
        migrations.AlterField(
            model_name='groupbuy',
            name='status',
            field=models.CharField(choices=[('recruiting', '모집중'), ('bidding', '입찰진행중'), ('final_selection_buyers', '구매자 최종선택중'), ('final_selection_seller', '판매자 최종선택중'), ('completed', '완료'), ('cancelled', '취소됨')], default='recruiting', max_length=30, verbose_name='상태'),
        ),
    ]
