# Generated by Django 3.2.11 on 2025-08-05 00:59

from django.db import migrations


def migrate_status_forward(apps, schema_editor):
    GroupBuy = apps.get_model('api', 'GroupBuy')
    
    # final_selection을 final_selection_buyers로 변경
    GroupBuy.objects.filter(status='final_selection').update(status='final_selection_buyers')
    
    # seller_confirmation을 final_selection_seller로 변경
    GroupBuy.objects.filter(status='seller_confirmation').update(status='final_selection_seller')


def migrate_status_backward(apps, schema_editor):
    GroupBuy = apps.get_model('api', 'GroupBuy')
    
    # final_selection_buyers를 final_selection으로 되돌리기
    GroupBuy.objects.filter(status='final_selection_buyers').update(status='final_selection')
    
    # final_selection_seller를 seller_confirmation으로 되돌리기
    GroupBuy.objects.filter(status='final_selection_seller').update(status='seller_confirmation')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_add_seller_selection_status'),
    ]

    operations = [
        migrations.RunPython(migrate_status_forward, migrate_status_backward),
    ]