# Generated by Django 3.2.11 on 2025-08-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_migrate_final_selection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_deleted_by_user',
            field=models.BooleanField(default=False, verbose_name='사용자 삭제 여부'),
        ),
        migrations.AddField(
            model_name='participation',
            name='is_deleted_by_user',
            field=models.BooleanField(default=False, verbose_name='사용자 삭제 여부'),
        ),
    ]
