# Generated by Django 3.2.11 on 2025-08-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20250806_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_sale_completed',
            field=models.BooleanField(default=False, verbose_name='판매완료 여부'),
        ),
        migrations.AddField(
            model_name='bid',
            name='sale_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='판매완료 일시'),
        ),
        migrations.AddField(
            model_name='participation',
            name='is_purchase_completed',
            field=models.BooleanField(default=False, verbose_name='구매완료 여부'),
        ),
        migrations.AddField(
            model_name='participation',
            name='purchase_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='구매완료 일시'),
        ),
        migrations.AlterField(
            model_name='groupbuy',
            name='status',
            field=models.CharField(choices=[('recruiting', '모집중'), ('bidding', '입찰진행중'), ('final_selection_buyers', '구매자 최종선택중'), ('final_selection_seller', '판매자 최종선택중'), ('in_progress', '거래중'), ('completed', '완료'), ('cancelled', '취소됨')], default='recruiting', max_length=30, verbose_name='상태'),
        ),
    ]
