# Generated by Django 3.2.11 on 2025-08-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20250807_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbuy',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='취소 사유'),
        ),
    ]
