# Generated by Django 3.2.11 on 2025-08-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_add_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbuy',
            name='buyer_completed',
            field=models.BooleanField(default=False, verbose_name='구매자 거래완료'),
        ),
        migrations.AddField(
            model_name='groupbuy',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='거래 완료 시간'),
        ),
        migrations.AddField(
            model_name='groupbuy',
            name='seller_completed',
            field=models.BooleanField(default=False, verbose_name='판매자 거래완료'),
        ),
        migrations.AlterField(
            model_name='groupbuy',
            name='status',
            field=models.CharField(choices=[('recruiting', '모집중'), ('final_selection_buyers', '구매자 최종선택중'), ('final_selection_seller', '판매자 최종선택중'), ('in_progress', '거래중'), ('completed', '완료'), ('cancelled', '취소됨')], default='recruiting', max_length=30, verbose_name='상태'),
        ),
    ]
