# Generated by Django 3.2.11 on 2025-08-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20250811_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remote_sales_certification',
            field=models.URLField(blank=True, null=True, verbose_name='비대면 판매 인증서 URL'),
        ),
    ]
