# Generated by Django 3.2.11 on 2025-08-13 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_add_remote_sales_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteSalesCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_file', models.URLField(verbose_name='인증서 파일 URL')),
                ('business_license_file', models.URLField(blank=True, null=True, verbose_name='사업자등록증 URL')),
                ('status', models.CharField(choices=[('pending', '심사중'), ('approved', '승인'), ('rejected', '거절'), ('expired', '만료')], default='pending', max_length=20, verbose_name='상태')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='제출일시')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='심사일시')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일시')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='만료일시')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='거절 사유')),
                ('admin_notes', models.TextField(blank=True, verbose_name='관리자 메모')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_certifications', to=settings.AUTH_USER_MODEL, verbose_name='심사자')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_sales_certifications', to=settings.AUTH_USER_MODEL, verbose_name='판매자')),
            ],
            options={
                'verbose_name': '비대면 판매 인증',
                'verbose_name_plural': '비대면 판매 인증',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='remotesalescertification',
            index=models.Index(fields=['seller', 'status'], name='api_remotes_seller__fd5b36_idx'),
        ),
        migrations.AddIndex(
            model_name='remotesalescertification',
            index=models.Index(fields=['status', 'submitted_at'], name='api_remotes_status_9b545f_idx'),
        ),
    ]
