# Generated by Django 3.2.11 on 2025-08-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20250813_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidtokenpurchase',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='주문 ID'),
        ),
        migrations.AddField(
            model_name='bidtokenpurchase',
            name='payment_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='결제 키'),
        ),
    ]
