# Generated by Django 3.2.11 on 2025-08-13 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20250813_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidTokenAdjustmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('add', '추가'), ('subtract', '차감'), ('grant_subscription', '구독권 부여')], max_length=20, verbose_name='조정 유형')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('reason', models.TextField(verbose_name='사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='조정일시')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_token_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='관리자')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_adjustment_logs', to=settings.AUTH_USER_MODEL, verbose_name='판매회원')),
            ],
            options={
                'verbose_name': '입찰권 조정 이력',
                'verbose_name_plural': '입찰권 조정 이력',
                'ordering': ['-created_at'],
            },
        ),
    ]
