# Generated by Django 3.2.11 on 2025-08-16 02:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_bidtokenadjustmentlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=100, verbose_name='파트너사명')),
                ('partner_code', models.CharField(help_text='추천 링크에 사용되는 고유 코드', max_length=20, unique=True, verbose_name='파트너 코드')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='수수료율 (%)')),
                ('bank_name', models.CharField(blank=True, max_length=50, verbose_name='은행명')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='계좌번호')),
                ('account_holder', models.CharField(blank=True, max_length=100, verbose_name='예금주')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('minimum_settlement_amount', models.PositiveIntegerField(default=50000, verbose_name='최소 정산 금액')),
            ],
            options={
                'verbose_name': '파트너사',
                'verbose_name_plural': '파트너사 관리',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='추천 코드'),
        ),
        migrations.CreateModel(
            name='ReferralRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(auto_now_add=True, verbose_name='가입일자')),
                ('subscription_status', models.CharField(choices=[('active', '활성'), ('cancelled', '해지'), ('paused', '휴면')], default='active', max_length=20, verbose_name='구독 상태')),
                ('subscription_amount', models.PositiveIntegerField(default=0, verbose_name='구독 금액')),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True, verbose_name='구독 시작일')),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True, verbose_name='구독 종료일')),
                ('ticket_count', models.PositiveIntegerField(default=0, verbose_name='구매 티켓 수')),
                ('ticket_amount', models.PositiveIntegerField(default=0, verbose_name='티켓 총 금액')),
                ('total_amount', models.PositiveIntegerField(default=0, verbose_name='총 결제 금액')),
                ('commission_amount', models.PositiveIntegerField(default=0, verbose_name='수수료 금액')),
                ('settlement_status', models.CharField(choices=[('pending', '미정산'), ('requested', '정산요청'), ('completed', '정산완료')], default='pending', max_length=20, verbose_name='정산 상태')),
                ('settlement_date', models.DateTimeField(blank=True, null=True, verbose_name='정산일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_records', to='api.partner', verbose_name='파트너사')),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_records', to=settings.AUTH_USER_MODEL, verbose_name='추천 회원')),
            ],
            options={
                'verbose_name': '추천 기록',
                'verbose_name_plural': '추천 기록 관리',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_amount', models.PositiveIntegerField(verbose_name='정산 금액')),
                ('tax_invoice_requested', models.BooleanField(default=False, verbose_name='세금계산서 발행 요청')),
                ('status', models.CharField(choices=[('pending', '요청됨'), ('processing', '처리중'), ('completed', '완료'), ('failed', '실패'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='처리 상태')),
                ('bank_name', models.CharField(max_length=50, verbose_name='은행명')),
                ('account_number', models.CharField(max_length=50, verbose_name='계좌번호')),
                ('account_holder', models.CharField(max_length=100, verbose_name='예금주')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('receipt_url', models.URLField(blank=True, verbose_name='영수증 URL')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='api.partner', verbose_name='파트너사')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_settlements', to=settings.AUTH_USER_MODEL, verbose_name='처리자')),
            ],
            options={
                'verbose_name': '파트너 정산',
                'verbose_name_plural': '파트너 정산 관리',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('signup', '신규 가입'), ('payment', '결제 완료'), ('cancellation', '구독 해지'), ('settlement', '정산 관련'), ('system', '시스템 알림')], max_length=20, verbose_name='알림 유형')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('message', models.TextField(verbose_name='메시지')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 상태')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='읽은 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.partner', verbose_name='파트너사')),
                ('referral_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.referralrecord', verbose_name='관련 추천 기록')),
            ],
            options={
                'verbose_name': '파트너 알림',
                'verbose_name_plural': '파트너 알림 관리',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(verbose_name='원본 URL')),
                ('short_code', models.CharField(max_length=10, unique=True, verbose_name='단축 코드')),
                ('short_url', models.URLField(verbose_name='단축 URL')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='클릭 수')),
                ('conversion_count', models.PositiveIntegerField(default=0, verbose_name='전환 수')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.partner', verbose_name='파트너사')),
            ],
            options={
                'verbose_name': '파트너 링크',
                'verbose_name_plural': '파트너 링크 관리',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddIndex(
            model_name='referralrecord',
            index=models.Index(fields=['partner', 'created_at'], name='api_referra_partner_018e01_idx'),
        ),
        migrations.AddIndex(
            model_name='referralrecord',
            index=models.Index(fields=['settlement_status'], name='api_referra_settlem_5598fc_idx'),
        ),
        migrations.AddIndex(
            model_name='partnersettlement',
            index=models.Index(fields=['partner', 'status'], name='api_partner_partner_d2f255_idx'),
        ),
        migrations.AddIndex(
            model_name='partnersettlement',
            index=models.Index(fields=['requested_at'], name='api_partner_request_a5f078_idx'),
        ),
        migrations.AddIndex(
            model_name='partnernotification',
            index=models.Index(fields=['partner', 'is_read'], name='api_partner_partner_52a2f9_idx'),
        ),
        migrations.AddIndex(
            model_name='partnernotification',
            index=models.Index(fields=['created_at'], name='api_partner_created_c19363_idx'),
        ),
    ]
