# Generated by Django 3.2.11 on 2025-08-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20250816_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='추가 데이터'),
        ),
        migrations.AlterField(
            model_name='category',
            name='detail_type',
            field=models.CharField(choices=[('none', '기본'), ('telecom', '통신'), ('electronics', '가전'), ('rental', '렌탈'), ('subscription', '구독'), ('internet', '인터넷'), ('internet_tv', '인터넷+TV')], default='none', max_length=20, verbose_name='상세 정보 유형'),
        ),
    ]
