# Generated by Django 3.2.11 on 2025-08-19 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessNumberVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_number', models.CharField(max_length=12, verbose_name='사업자등록번호')),
                ('status', models.CharField(choices=[('pending', '검증 대기'), ('valid', '유효'), ('invalid', '무효'), ('error', '검증 오류')], default='pending', max_length=20, verbose_name='검증 상태')),
                ('business_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='상호명')),
                ('representative_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='대표자명')),
                ('business_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='사업상태')),
                ('business_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='업종')),
                ('establishment_date', models.DateField(blank=True, null=True, verbose_name='개업일')),
                ('address', models.TextField(blank=True, null=True, verbose_name='사업장 주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='검증 요청일')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='검증 완료일')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='오류 메시지')),
                ('api_response', models.JSONField(blank=True, default=dict, help_text='국세청 API 응답 데이터', verbose_name='API 응답')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_verifications', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사업자번호 검증',
                'verbose_name_plural': '사업자번호 검증',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='businessnumberverification',
            index=models.Index(fields=['business_number'], name='api_busines_busines_df8449_idx'),
        ),
        migrations.AddIndex(
            model_name='businessnumberverification',
            index=models.Index(fields=['user', 'status'], name='api_busines_user_id_5c0153_idx'),
        ),
    ]
