# Generated by Django 3.2.11 on 2025-08-20 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_add_business_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='representative_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='대표자명'),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('verification_code', models.CharField(max_length=6, verbose_name='인증 코드')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('verified', '인증완료'), ('expired', '만료됨'), ('failed', '실패')], default='pending', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('expires_at', models.DateTimeField(verbose_name='만료일시')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='인증일시')),
                ('attempt_count', models.IntegerField(default=0, verbose_name='시도 횟수')),
                ('max_attempts', models.IntegerField(default=5, verbose_name='최대 시도 횟수')),
                ('purpose', models.CharField(default='password_reset', help_text='password_reset: 비밀번호 재설정, signup: 회원가입, change_email: 이메일 변경', max_length=50, verbose_name='용도')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('additional_info', models.JSONField(blank=True, default=dict, help_text='인증 시 제공된 추가 정보 (username 등)', verbose_name='추가 정보')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_verifications', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '이메일 인증',
                'verbose_name_plural': '이메일 인증',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['email', 'status'], name='api_emailve_email_658486_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['verification_code'], name='api_emailve_verific_5f403d_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['created_at'], name='api_emailve_created_e967bf_idx'),
        ),
    ]
