# Generated by Django 3.2.11 on 2025-08-23 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_add_representative_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbuy',
            name='status',
            field=models.CharField(choices=[('recruiting', '모집중'), ('bidding', '입찰진행중'), ('final_selection_buyers', '구매자 최종선택중'), ('final_selection_seller', '판매자 최종선택중'), ('in_progress', '거래중'), ('completed', '완료'), ('cancelled', '취소됨')], default='recruiting', max_length=30, verbose_name='상태'),
        ),
        migrations.CreateModel(
            name='GroupBuyInternetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(blank=True, choices=[('SKT', 'SK브로드밴드'), ('KT', 'KT'), ('LGU', 'LG U+')], max_length=10, verbose_name='통신사')),
                ('subscription_type', models.CharField(choices=[('new', '신규가입'), ('transfer', '통신사이동')], max_length=20, verbose_name='가입유형')),
                ('speed', models.CharField(blank=True, choices=[('100M', '100M'), ('200M', '200M'), ('500M', '500M'), ('1G', '1G'), ('2.5G', '2.5G'), ('5G', '5G'), ('10G', '10G')], max_length=10, verbose_name='인터넷 속도')),
                ('has_tv', models.BooleanField(default=False, verbose_name='TV 포함 여부')),
                ('contract_period', models.CharField(default='24개월', max_length=20, verbose_name='약정기간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groupbuy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internet_detail', to='api.groupbuy')),
            ],
            options={
                'verbose_name': '공구 인터넷 상세정보',
                'verbose_name_plural': '공구 인터넷 상세정보',
            },
        ),
    ]
