# Generated by Django 3.2.11 on 2025-08-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20250823_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbuyinternetdetail',
            name='additional_benefits',
            field=models.TextField(blank=True, help_text='예: 넷플릭스 무료, 와이파이 공유기 제공', verbose_name='추가 혜택'),
        ),
        migrations.AddField(
            model_name='groupbuyinternetdetail',
            name='gift_info',
            field=models.TextField(blank=True, help_text='예: 신세계 상품권 10만원, 현금 캐시백 5만원', verbose_name='사은품 정보'),
        ),
        migrations.AddField(
            model_name='groupbuyinternetdetail',
            name='installation_fee',
            field=models.CharField(blank=True, help_text='예: 무료, 30,000원', max_length=50, verbose_name='설치비'),
        ),
        migrations.AddField(
            model_name='groupbuyinternetdetail',
            name='monthly_fee',
            field=models.CharField(blank=True, help_text='예: 30,000원, 4만원대', max_length=50, verbose_name='월 요금'),
        ),
        migrations.AddField(
            model_name='groupbuyinternetdetail',
            name='product_plan',
            field=models.CharField(blank=True, help_text='예: 기가, 광랜, 슬림, 베이직, 에센스', max_length=50, verbose_name='상품 플랜명'),
        ),
        migrations.AddField(
            model_name='groupbuyinternetdetail',
            name='raw_product_title',
            field=models.CharField(blank=True, help_text='파싱 전 원본 상품 제목', max_length=255, verbose_name='원본 상품명'),
        ),
        migrations.AddField(
            model_name='groupbuyinternetdetail',
            name='tv_channels',
            field=models.CharField(blank=True, help_text='예: 기본형, 프리미엄, 200채널', max_length=100, verbose_name='TV 채널 정보'),
        ),
    ]
