# Generated by Django 3.2.11 on 2025-08-26 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_review_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(choices=[('002', '산업은행'), ('003', '기업은행'), ('004', 'KB국민은행'), ('005', '수협은행'), ('007', '수협중앙회'), ('008', '수출입은행'), ('011', 'NH농협은행'), ('012', '농협중앙회'), ('020', '우리은행'), ('023', 'SC제일은행'), ('027', '한국씨티은행'), ('031', '대구은행'), ('032', '부산은행'), ('034', '광주은행'), ('035', '제주은행'), ('037', '전북은행'), ('039', '경남은행'), ('045', '새마을금고'), ('048', '신협'), ('050', '저축은행'), ('064', '산림조합'), ('071', '우체국'), ('081', '하나은행'), ('088', '신한은행'), ('089', '케이뱅크'), ('090', '카카오뱅크'), ('092', '토스뱅크')], max_length=3, verbose_name='은행코드')),
                ('bank_name', models.CharField(max_length=20, verbose_name='은행명')),
                ('account_number', models.CharField(max_length=50, verbose_name='계좌번호')),
                ('account_holder_name', models.CharField(max_length=50, verbose_name='예금주명')),
                ('account_holder_info', models.CharField(blank=True, help_text='생년월일(YYMMDD) 또는 사업자등록번호', max_length=20, verbose_name='예금주 정보')),
                ('is_business', models.BooleanField(default=False, verbose_name='사업자 계좌 여부')),
                ('verification_status', models.CharField(choices=[('pending', '인증대기'), ('verified', '인증완료'), ('failed', '인증실패')], default='pending', max_length=10, verbose_name='인증 상태')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='인증 일시')),
                ('verification_result', models.TextField(blank=True, verbose_name='인증 결과')),
                ('is_primary', models.BooleanField(default=True, verbose_name='주 계좌 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='api.partner', verbose_name='파트너')),
            ],
            options={
                'verbose_name': '파트너 은행계좌',
                'verbose_name_plural': '파트너 은행계좌',
                'ordering': ['-created_at'],
            },
        ),
    ]
