# Generated by Django 3.2.11 on 2025-08-26 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_partnerbankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True, verbose_name='주문번호')),
                ('payment_method', models.CharField(choices=[('inicis', '이니시스'), ('toss', '토스페이먼츠'), ('kakao', '카카오페이'), ('naver', '네이버페이')], max_length=20, verbose_name='결제수단')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='결제금액')),
                ('product_name', models.CharField(max_length=200, verbose_name='상품명')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('completed', '완료'), ('failed', '실패'), ('cancelled', '취소'), ('refunded', '환불')], default='pending', max_length=20, verbose_name='상태')),
                ('buyer_name', models.CharField(blank=True, max_length=100, verbose_name='구매자명')),
                ('buyer_tel', models.CharField(blank=True, max_length=20, verbose_name='구매자 전화번호')),
                ('buyer_email', models.EmailField(blank=True, max_length=254, verbose_name='구매자 이메일')),
                ('tid', models.CharField(blank=True, max_length=200, null=True, verbose_name='거래번호')),
                ('payment_data', models.JSONField(blank=True, default=dict, verbose_name='결제 데이터')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='취소 사유')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='취소일시')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='환불금액')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '결제',
                'verbose_name_plural': '결제 목록',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='payments_user_id_2c5fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order_id'], name='payments_order_i_b32b33_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tid'], name='payments_tid_6256f8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_d621e5_idx'),
        ),
    ]
