# Generated by Django 3.2.11 on 2025-08-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20250826_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('inicis', '이니시스'), ('kakao', '카카오페이'), ('naver', '네이버페이')], max_length=20, verbose_name='결제수단'),
        ),
    ]
