# Generated by Django 3.2.11 on 2025-08-27 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_payment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('category', models.CharField(choices=[('general', '일반공지'), ('event', '이벤트'), ('update', '업데이트'), ('maintenance', '점검안내'), ('important', '중요공지')], default='general', max_length=20, verbose_name='카테고리')),
                ('content', models.TextField(help_text='HTML 태그를 사용할 수 있습니다.', verbose_name='내용 (HTML)')),
                ('summary', models.TextField(blank=True, help_text='목록에 표시될 간단한 요약 (선택사항)', max_length=500, verbose_name='요약')),
                ('is_pinned', models.BooleanField(default=False, help_text='상단에 고정할 중요 공지사항', verbose_name='상단 고정')),
                ('is_published', models.BooleanField(default=True, verbose_name='게시 여부')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('published_at', models.DateTimeField(blank=True, help_text='미래 날짜를 설정하면 예약 게시됩니다.', null=True, verbose_name='게시일')),
                ('meta_title', models.CharField(blank=True, help_text='SEO를 위한 메타 제목 (비워두면 제목 사용)', max_length=200, verbose_name='메타 제목')),
                ('meta_description', models.TextField(blank=True, help_text='SEO를 위한 메타 설명', max_length=500, verbose_name='메타 설명')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='notices/thumbnails/%Y/%m/', verbose_name='썸네일 이미지')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notices/images/%Y/%m/', verbose_name='이미지')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='캡션')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 일시')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.notice', verbose_name='공지사항')),
            ],
            options={
                'verbose_name': '공지사항 이미지',
                'verbose_name_plural': '공지사항 이미지',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.notice', verbose_name='공지사항')),
            ],
            options={
                'verbose_name': '공지사항 댓글',
                'verbose_name_plural': '공지사항 댓글',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['-is_pinned', '-created_at'], name='api_notice_is_pinn_8ad498_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['is_published', 'published_at'], name='api_notice_is_publ_dc645d_idx'),
        ),
    ]
