# Generated by Django 3.2.11 on 2025-08-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vbank_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='입금기한'),
        ),
        migrations.AddField(
            model_name='payment',
            name='vbank_holder',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='예금주명'),
        ),
        migrations.AddField(
            model_name='payment',
            name='vbank_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='입금은행명'),
        ),
        migrations.AddField(
            model_name='payment',
            name='vbank_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='입금계좌번호'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', '대기중'), ('waiting_deposit', '입금대기'), ('completed', '완료'), ('failed', '실패'), ('cancelled', '취소'), ('refunded', '환불')], default='pending', max_length=20, verbose_name='상태'),
        ),
    ]
