# Generated by Django 3.2.11 on 2025-09-05 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_penalty_improvements'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='환불 사유')),
                ('status', models.CharField(choices=[('pending', '검토중'), ('approved', '승인'), ('rejected', '거부'), ('completed', '완료')], default='pending', max_length=20, verbose_name='상태')),
                ('request_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='환불 요청 금액')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='관리자 메모')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일시')),
                ('refund_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='환불 방법')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='실제 환불금액')),
                ('refund_data', models.JSONField(blank=True, default=dict, verbose_name='환불 처리 데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '환불 요청',
                'verbose_name_plural': '환불 요청 목록',
                'db_table': 'refund_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', '-release_date'], 'verbose_name': '상품', 'verbose_name_plural': '상품 관리'},
        ),
        migrations.RemoveIndex(
            model_name='notice',
            name='api_notice_show_in_9a3e5f_idx',
        ),
        migrations.AlterField(
            model_name='notice',
            name='popup_height',
            field=models.IntegerField(default=600, help_text='팝업 창 높이 (픽셀, 이미지 팝업의 경우 자동 조정)', verbose_name='팝업 높이'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='popup_image',
            field=models.ImageField(blank=True, help_text='팝업에 표시할 이미지 (이미지/혼합 타입에서 사용)', null=True, upload_to='notices/popups/%Y/%m/', verbose_name='팝업 이미지'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['show_in_main', 'main_display_order'], name='api_notice_show_in_a51771_idx'),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='api.payment', verbose_name='결제 정보'),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL, verbose_name='처리자'),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['user', '-created_at'], name='refund_requ_user_id_986987_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['payment', '-created_at'], name='refund_requ_payment_08f47c_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['status', '-created_at'], name='refund_requ_status_9f855c_idx'),
        ),
    ]
