# Generated by Django 5.1.4 on 2025-09-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0074_auto_20250905_1632"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="payment",
            new_name="api_payment_user_id_78aa4b_idx",
            old_name="payments_user_id_2c5fd7_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="api_payment_order_i_e2d2f5_idx",
            old_name="payments_order_i_b32b33_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="api_payment_tid_514c77_idx",
            old_name="payments_tid_6256f8_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="api_payment_status_f29f0b_idx",
            old_name="payments_status_d621e5_idx",
        ),
        migrations.RenameIndex(
            model_name="refundrequest",
            new_name="api_refund__user_id_abf5b5_idx",
            old_name="refund_requ_user_id_986987_idx",
        ),
        migrations.RenameIndex(
            model_name="refundrequest",
            new_name="api_refund__payment_085b94_idx",
            old_name="refund_requ_payment_08f47c_idx",
        ),
        migrations.RenameIndex(
            model_name="refundrequest",
            new_name="api_refund__status_23f60a_idx",
            old_name="refund_requ_status_9f855c_idx",
        ),
        migrations.AlterModelTable(
            name="payment",
            table="api_payments",
        ),
        migrations.AlterModelTable(
            name="refundrequest",
            table="api_refund_requests",
        ),
    ]
