# Generated by Django 5.0.7 on 2025-01-22 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0079_add_page_display_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, max_length=20, verbose_name='상품타입')),
                ('item_id', models.IntegerField(blank=True, null=True, verbose_name='상품ID')),
                ('reported_nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='신고대상 닉네임')),
                ('reported_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='신고대상 연락처')),
                ('report_type', models.CharField(choices=[('fake_listing', '허위매물'), ('fraud', '사기'), ('abusive_language', '욕설'), ('inappropriate_behavior', '부적절한 행동'), ('spam', '스팸/광고'), ('other', '기타')], max_length=30, verbose_name='신고유형')),
                ('title', models.CharField(max_length=200, verbose_name='신고제목')),
                ('description', models.TextField(verbose_name='신고내용')),
                ('evidence', models.TextField(blank=True, help_text='스크린샷 URL, 대화 내용 등', verbose_name='증거자료')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('processing', '처리중'), ('resolved', '해결됨'), ('rejected', '거부됨')], default='pending', max_length=20, verbose_name='상태')),
                ('admin_notes', models.TextField(blank=True, verbose_name='관리자메모')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신고일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_reports', to=settings.AUTH_USER_MODEL, verbose_name='처리자')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to=settings.AUTH_USER_MODEL, verbose_name='신고대상')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
            ],
            options={
                'verbose_name': '통합 신고',
                'verbose_name_plural': '통합 신고 관리',
                'db_table': 'unified_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnifiedPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_type', models.CharField(choices=[('auto_report', '신고 누적'), ('manual_admin', '관리자 수동'), ('trade_violation', '거래 위반'), ('fake_listing', '허위매물'), ('abusive_behavior', '악성 행위')], max_length=20, verbose_name='패널티유형')),
                ('reason', models.TextField(verbose_name='패널티사유')),
                ('duration_hours', models.IntegerField(default=24, help_text='시간 단위로 입력 (예: 24시간 = 1일, 168시간 = 7일)', verbose_name='패널티시간')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='시작일')),
                ('status', models.CharField(choices=[('active', '활성'), ('expired', '만료'), ('revoked', '해제')], default='active', max_length=20, verbose_name='상태')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='해제일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_penalties', to=settings.AUTH_USER_MODEL, verbose_name='발령자')),
                ('related_reports', models.ManyToManyField(blank=True, related_name='penalties', to='api.unifiedreport', verbose_name='관련신고')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_penalties', to=settings.AUTH_USER_MODEL, verbose_name='해제자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to=settings.AUTH_USER_MODEL, verbose_name='패널티대상')),
            ],
            options={
                'verbose_name': '통합 패널티',
                'verbose_name_plural': '통합 패널티 관리',
                'db_table': 'unified_penalties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnifiedDeletePenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='삭제된 상품명')),
                ('item_type', models.CharField(max_length=20, verbose_name='상품타입')),
                ('had_offers', models.BooleanField(default=False, verbose_name='견적 존재 여부')),
                ('penalty_end', models.DateTimeField(verbose_name='패널티 종료 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_penalties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '통합 삭제 패널티',
                'verbose_name_plural': '통합 삭제 패널티 관리',
                'db_table': 'unified_delete_penalties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='unifiedreport',
            index=models.Index(fields=['status', '-created_at'], name='unified_rep_status_49feb0_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedreport',
            index=models.Index(fields=['reported_user', 'status'], name='unified_rep_reporte_bf5ac2_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedreport',
            index=models.Index(fields=['reporter', '-created_at'], name='unified_rep_reporte_aa6354_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedpenalty',
            index=models.Index(fields=['user', 'status'], name='unified_pen_user_id_dbb0ef_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedpenalty',
            index=models.Index(fields=['status', '-created_at'], name='unified_pen_status_1c3f89_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieddeletepenalty',
            index=models.Index(fields=['user', 'penalty_end'], name='unified_del_user_id_22a5e7_idx'),
        ),
        migrations.AddIndex(
            model_name='unifieddeletepenalty',
            index=models.Index(fields=['-created_at'], name='unified_del_created_5e1a76_idx'),
        ),
    ]