# Generated by Claude for CustomNoShowReport model

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_add_twa_app_fields_to_popup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNoShowReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('buyer_noshow', '구매자 노쇼'), ('seller_noshow', '판매자 노쇼')], max_length=20, verbose_name='신고 유형')),
                ('content', models.TextField(verbose_name='신고 내용')),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='custom_noshow_reports/', verbose_name='증빙 이미지')),
                ('evidence_image_2', models.ImageField(blank=True, null=True, upload_to='custom_noshow_reports/', verbose_name='증빙 이미지 2')),
                ('evidence_image_3', models.ImageField(blank=True, null=True, upload_to='custom_noshow_reports/', verbose_name='증빙 이미지 3')),
                ('status', models.CharField(choices=[('pending', '처리중'), ('completed', '처리완료'), ('on_hold', '보류중')], default='pending', max_length=20, verbose_name='처리 상태')),
                ('admin_comment', models.TextField(blank=True, verbose_name='관리자 코멘트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신고일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일')),
                ('edit_count', models.IntegerField(default=0, verbose_name='수정 횟수')),
                ('last_edited_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 수정 시간')),
                ('noshow_buyers', models.JSONField(blank=True, default=list, verbose_name='노쇼 구매자 목록')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='취소 여부')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='취소 시간')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='취소 사유')),
                ('custom_groupbuy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noshow_reports', to='api.customgroupbuy', verbose_name='커스텀 공구')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noshow_reports', to='api.customparticipant', verbose_name='참여 정보')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_custom_noshow_reports', to=settings.AUTH_USER_MODEL, verbose_name='처리자')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_noshow_reports_received', to=settings.AUTH_USER_MODEL, verbose_name='피신고자')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_noshow_reports_made', to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
            ],
            options={
                'verbose_name': '커스텀 노쇼 신고',
                'verbose_name_plural': '커스텀 노쇼 신고 관리',
                'db_table': 'custom_noshow_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='customnoshowreport',
            constraint=models.UniqueConstraint(fields=('reporter', 'reported_user', 'custom_groupbuy'), name='unique_custom_noshow_report_per_user_groupbuy'),
        ),
    ]
