# Generated by Django 4.2 for fixing cleaning/moving consultation flows

from django.db import migrations


# 청소·이사 플로우 데이터 (청소업체 카테고리에 저장)
CLEANING_MOVING_FLOWS = [
    {
        'step_number': 1,
        'question': '어떤 서비스가 필요하세요?',
        'options': [
            {'key': 'moving', 'label': '이사 서비스', 'icon': '🚚', 'description': '가정/사무실 이사, 포장이사 등'},
            {'key': 'cleaning', 'label': '청소 서비스', 'icon': '🧹', 'description': '입주청소, 정기청소, 특수청소 등'},
            {'key': 'custom', 'label': '직접 입력', 'icon': '📝', 'is_custom_input': True},
        ]
    },
    # 이사 선택 시 질문들
    {
        'step_number': 2,
        'question': '어떤 이사인가요?',
        'depends_on_step': 1,
        'depends_on_options': ['moving'],
        'options': [
            {'key': 'home_move', 'label': '가정 이사', 'icon': '🏠'},
            {'key': 'office_move', 'label': '사무실 이사', 'icon': '🏢'},
            {'key': 'small_move', 'label': '원룸/소형 이사', 'icon': '📦'},
            {'key': 'long_distance', 'label': '장거리 이사', 'icon': '🚛'},
            {'key': 'custom', 'label': '직접 입력', 'icon': '📝', 'is_custom_input': True},
        ]
    },
    # 청소 선택 시 질문들
    {
        'step_number': 2,
        'question': '어떤 청소가 필요하세요?',
        'depends_on_step': 1,
        'depends_on_options': ['cleaning'],
        'options': [
            {'key': 'move_in', 'label': '입주 청소', 'icon': '🏠'},
            {'key': 'move_out', 'label': '이사 청소', 'icon': '📦'},
            {'key': 'regular', 'label': '정기 청소', 'icon': '✨'},
            {'key': 'special', 'label': '특수 청소', 'icon': '🧽', 'description': '에어컨, 새집증후군 등'},
            {'key': 'office', 'label': '사무실/상가 청소', 'icon': '🏢'},
            {'key': 'custom', 'label': '직접 입력', 'icon': '📝', 'is_custom_input': True},
        ]
    },
    {
        'step_number': 3,
        'question': '공간 크기는?',
        'options': [
            {'key': 'studio', 'label': '원룸/투룸', 'icon': '🛏️'},
            {'key': 'under_20', 'label': '20평 미만', 'icon': '📐'},
            {'key': '20_to_30', 'label': '20~30평', 'icon': '📏'},
            {'key': '30_to_40', 'label': '30~40평', 'icon': '🏠'},
            {'key': 'over_40', 'label': '40평 이상', 'icon': '🏡'},
            {'key': 'custom', 'label': '직접 입력', 'icon': '📝', 'is_custom_input': True},
        ]
    },
    {
        'step_number': 4,
        'question': '희망 날짜는?',
        'options': [
            {'key': 'this_week', 'label': '이번 주', 'icon': '📅'},
            {'key': 'next_week', 'label': '다음 주', 'icon': '🗓️'},
            {'key': 'within_month', 'label': '한 달 이내', 'icon': '📆'},
            {'key': 'specific_date', 'label': '특정 날짜 지정', 'icon': '✅'},
            {'key': 'flexible', 'label': '협의 가능', 'icon': '🤝'},
            {'key': 'custom', 'label': '직접 입력', 'icon': '📝', 'is_custom_input': True},
        ]
    },
    # 이사: 추가 서비스
    {
        'step_number': 5,
        'question': '추가 서비스가 필요하세요?',
        'depends_on_step': 1,
        'depends_on_options': ['moving'],
        'options': [
            {'key': 'packing', 'label': '포장 서비스', 'icon': '📦'},
            {'key': 'storage', 'label': '보관 서비스', 'icon': '🏪'},
            {'key': 'disposal', 'label': '폐기물 처리', 'icon': '🗑️'},
            {'key': 'cleaning_too', 'label': '청소도 함께', 'icon': '🧹'},
            {'key': 'none', 'label': '없음', 'icon': '✅'},
            {'key': 'custom', 'label': '직접 입력', 'icon': '📝', 'is_custom_input': True},
        ]
    },
    # 청소: 추가 요청
    {
        'step_number': 5,
        'question': '추가 요청사항이 있으세요?',
        'depends_on_step': 1,
        'depends_on_options': ['cleaning'],
        'options': [
            {'key': 'aircon', 'label': '에어컨 청소 포함', 'icon': '❄️'},
            {'key': 'kitchen', 'label': '주방 집중 청소', 'icon': '🍳'},
            {'key': 'bathroom', 'label': '욕실 집중 청소', 'icon': '🚿'},
            {'key': 'window', 'label': '창문 청소 포함', 'icon': '🪟'},
            {'key': 'none', 'label': '기본 청소만', 'icon': '✅'},
            {'key': 'custom', 'label': '직접 입력', 'icon': '📝', 'is_custom_input': True},
        ]
    },
]


def populate_cleaning_moving_flows(apps, schema_editor):
    """청소 전문 카테고리에 청소·이사 플로우 데이터 생성"""
    LocalBusinessCategory = apps.get_model('api', 'LocalBusinessCategory')
    ConsultationFlow = apps.get_model('api', 'ConsultationFlow')
    ConsultationFlowOption = apps.get_model('api', 'ConsultationFlowOption')

    # 청소 전문 카테고리 찾기
    try:
        category = LocalBusinessCategory.objects.get(name='청소 전문')
    except LocalBusinessCategory.DoesNotExist:
        # 청소 전문이 없으면 이사 전문 시도
        try:
            category = LocalBusinessCategory.objects.get(name='이사 전문')
        except LocalBusinessCategory.DoesNotExist:
            print('청소 전문/이사 전문 카테고리 없음 - 건너뜀')
            return

    # 해당 카테고리의 기존 플로우 삭제
    ConsultationFlow.objects.filter(category=category).delete()

    # 새 플로우 생성
    for idx, flow_data in enumerate(CLEANING_MOVING_FLOWS):
        flow = ConsultationFlow.objects.create(
            category=category,
            step_number=flow_data['step_number'],
            question=flow_data['question'],
            is_required=flow_data.get('is_required', True),
            depends_on_step=flow_data.get('depends_on_step'),
            depends_on_options=flow_data.get('depends_on_options', []),
            order_index=idx,
            is_active=True,
        )

        # 옵션 생성
        for opt_idx, option_data in enumerate(flow_data.get('options', [])):
            ConsultationFlowOption.objects.create(
                flow=flow,
                key=option_data['key'],
                label=option_data['label'],
                icon=option_data.get('icon', ''),
                description=option_data.get('description', ''),
                is_custom_input=option_data.get('is_custom_input', False),
                order_index=opt_idx,
                is_active=True,
            )

    print(f'청소업체 카테고리 플로우 생성 완료 ({len(CLEANING_MOVING_FLOWS)}개)')


def reverse_populate(apps, schema_editor):
    """롤백 시 데이터 삭제"""
    LocalBusinessCategory = apps.get_model('api', 'LocalBusinessCategory')
    ConsultationFlow = apps.get_model('api', 'ConsultationFlow')

    try:
        category = LocalBusinessCategory.objects.get(name='청소 전문')
        ConsultationFlow.objects.filter(category=category).delete()
    except LocalBusinessCategory.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_add_logo_to_consultation_flow_option'),
    ]

    operations = [
        migrations.RunPython(populate_cleaning_moving_flows, reverse_populate),
    ]
