# Generated by Django 4.2.18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),  # Region 모델이 있는 앱
        ('used_phones', '0002_add_url_fields'),
    ]

    operations = [
        # body_only 필드 추가
        migrations.AddField(
            model_name='usedphone',
            name='body_only',
            field=models.BooleanField(default=False, verbose_name='본체만'),
        ),
        
        # UsedPhoneRegion 모델 생성
        migrations.CreateModel(
            name='UsedPhoneRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_phone_regions', to='api.region', verbose_name='지역')),
                ('used_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='used_phones.usedphone', verbose_name='중고폰')),
            ],
            options={
                'verbose_name': '중고폰 지역',
                'verbose_name_plural': '중고폰 지역 관리',
                'db_table': 'used_phone_regions',
                'unique_together': {('used_phone', 'region')},
            },
        ),
    ]