# Generated by Django 4.2.18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('used_phones', '0003_add_body_only_and_regions'),
    ]

    operations = [
        # accessories 필드를 nullable로 변경
        migrations.AlterField(
            model_name='usedphone',
            name='accessories',
            field=models.JSONField(blank=True, null=True, default=list),
        ),
    ]