# Generated by Django 5.1.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('used_phones', '0009_tradecancellation_and_price_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedphone',
            name='seller_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='판매자 완료 시간'),
        ),
        migrations.AddField(
            model_name='usedphone',
            name='buyer_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='구매자 완료 시간'),
        ),
    ]