name: Django Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dungji_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create .env file
      run: |
        echo "SECRET_KEY=django-insecure-test-key-for-github-actions-only" >> .env
        echo "DEBUG=True" >> .env
        echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/dungji_test" >> .env
        echo "ENVIRONMENT=test" >> .env
        echo "ALLOWED_HOSTS=localhost,127.0.0.1" >> .env
        echo "DB_NAME=dungji_test" >> .env
        echo "DB_USER=postgres" >> .env
        echo "DB_PASSWORD=postgres" >> .env
        echo "DB_HOST=localhost" >> .env
        echo "DB_PORT=5432" >> .env
        echo "USE_S3=False" >> .env
        echo "MEDIA_URL=/media/" >> .env
        echo "STATIC_URL=/static/" >> .env
        
    - name: Check Django settings
      run: |
        python manage.py check --deploy || true
        
    - name: Run migrations
      run: |
        python manage.py migrate --no-input
        
    - name: Run tests  
      run: |
        python manage.py test api --no-input -v 2